apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usermanagement-app
  namespace: usermanagement-app
spec:
  project: default
  source:
    repoURL:
    targetVersion: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: usermanagement-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true