apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usermanagement
  namespace: usermanagement-app
spec:
  project: default
  
  source:
    repoURL: https://github.com/alexmurithi/usermanagement-devops.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: usermanagement-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true