apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-deployment
  template:
    metadata:
      name: user-management-deployment
      labels:
        app: user-management-deployment
    spec:
      containers:
        - name: user-management-deployment
          image: alexacrregistry.azurecr.io/user-management:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: '/actuator/health/liveness'
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: '/actuator/health/readiness'
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "750m"
          env:
            - name: DATABASE_HOST
              value: 'alexazureserver.mysql.database.azure.com'
            - name: DATABASE_USERNAME
              value: 'user'
            - name: DATABASE_PASSWORD
              value: 'Pass@word'
            - name: DATABASE_NAME
              value: 'user-management'    