apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-deployment
  template:
    metadata:
      name: user-management-deployment
      labels:
        app: user-management-deployment
    spec:
      containers:
        - name: user-management-deployment
          image: alexacrregistry.azurecr.io/user-management:latest
          ports:
            - containerPort: 80
          readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 15
          livenessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 15
          env:
            - name: DATABASE_HOST
              value: 'alexazureserver.mysql.database.azure.com'
            - name: DATABASE_USERNAME
              value: 'user'
            - name: DATABASE_PASSWORD
              value: 'Pass@word'
            - name: DATABASE_NAME
              value: 'user-management'    