apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-deployment
  template:
    metadata:
      name: user-management-deployment
      labels:
        app: user-management-deployment
    spec:
      containers:
        - name: user-management-deployment
          image: alexacrregistry.azurecr.io/user-management:latest
          ports:
            - containerPort: 8080

      