  name: Deploy With ArgoCD
  on:
    push:
      branches:
        - master
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}

        - name: Login to ACR
          run: |
            az acr login -n ${{secrets.AZURE_CONTAINER_REGISTRY}}

        - name: Get AKS Credentials
          run: |
            az aks get-credentials -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_AKS_CLUSTER}} --overwrite-existing
            
        - name: Install ArgoCD
          run: |
            if ! kubectl get ns argocd > /dev/null 2>&1; then
              kubectl create namespace argocd
              kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
            else
              echo "ArgoCD is already installed."
            fi

        - name: Install ArgoCD CLI
          run: |
            if ! command -v argocd &> /dev/null; then
              curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
              chmod +x /usr/local/bin/argocd
            else
              echo "ArgoCD CLI is already installed."
            fi
        - name: Start port forwarding
          run: |
            kubectl port-forward svc/argocd-server -n argocd 8080:443 &
            sleep 10 # Wait a bit for port forwarding to establish
            
